[build]
target = "x86_64-unknown-linux-gnu"
rustflags = [
    "-Zlocation-detail=none",
    "-Zprint-type-sizes"
]

[unstable]
build-std = ["panic_abort", "core"]
build-std-features=["panic_immediate_abort"]